platform :ios, '13.0'
require 'fileutils'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  mantle_public_headers = Dir.glob(File.join(Dir.home, 'Library', 'Caches', 'CocoaPods', 'Pods', 'Release', 'Mantle', '*', 'Mantle', 'include', '*.h'))
  unless mantle_public_headers.empty?
    mantle_header_dir = File.join(installer.sandbox.root, 'Mantle')
    mantle_public_headers.each do |header|
      FileUtils.cp(header, File.join(mantle_header_dir, File.basename(header)))
    end
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    next unless target.name == 'flutter_image_compress_common'

    target.build_configurations.each do |config|
      paths = config.build_settings['HEADER_SEARCH_PATHS'] || ['$(inherited)']
      paths = paths.split(' ') if paths.is_a?(String)
      paths << '"${PODS_ROOT}"'
      config.build_settings['HEADER_SEARCH_PATHS'] = paths.uniq
    end
  end
end
